name: go mod
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: "read"

env:
  GO_VERSION: "1.21"

jobs:
  release:
    name: "go mod"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5" # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: tidy
        run: |
          go mod tidy && git diff --exit-code
