name: check license
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: license check
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: Syu-fu/go-licenses@3840b4537069841abab6001c5a8900ebe15594e4
