name: check license
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: license check
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: Syu-fu/go-licenses@3840b4537069841abab6001c5a8900ebe15594e4
