name: check license
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: license check
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: Syu-fu/go-licenses@3840b4537069841abab6001c5a8900ebe15594e4
