name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: "read"

env:
  GO_VERSION: "1.22"

jobs:
  release:
    name: "lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a" # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
        with:
          version: v1.59
