name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: "read"

env:
  GO_VERSION: "1.22"

jobs:
  release:
    name: "lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed" # v5.1.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: v1.59
