name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: "read"

env:
  GO_VERSION: "1.22"

jobs:
  release:
    name: "lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34" # v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: golangci/golangci-lint-action@051d91933864810ecd5e2ea2cfd98f6a5bca5347 # v6.3.2
        with:
          version: v1.59
