name: release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: "write"

env:
  GO_VERSION: "1.22"

jobs:
  release:
    name: "release"
    runs-on: "ubuntu-latest"
    env:
      WORKINGDIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34" # v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: "goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3" # v6.2.1
        with:
          version: "latest"
          args: "release --clean"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
