name: release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: "write"

env:
  GO_VERSION: "1.22"

jobs:
  release:
    name: "release"
    runs-on: "ubuntu-latest"
    env:
      WORKINGDIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5" # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: "goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552" # v6.3.0
        with:
          version: "latest"
          args: "release --clean"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
