name: test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: "write"

env:
  GO_VERSION: "1.22"

jobs:
  release:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34" # v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run coverage
        run: |
          go test -shuffle on -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@494b2847891f4dd3b10f6704ca533367dbb7493d # v0.3.0
