name: test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: "write"

env:
  GO_VERSION: "1.22"

jobs:
  release:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: "actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5" # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run coverage
        run: |
          go test -shuffle on -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@aa507d98fb11c2b4dffa1b731e0786f50fd8ec93 # v0.3.1
